//
//  GeneratedPluginRegistrant.h
//  Runner
//
//  This file is auto-generated by Flutter at build time (flutter pub get / flutter build).
//  Do NOT edit manually.  If this file is missing, run `flutter pub get` in the project root.
//

#ifndef GeneratedPluginRegistrant_h
#define GeneratedPluginRegistrant_h

#import <Flutter/Flutter.h>

@interface GeneratedPluginRegistrant : NSObject
+ (void)registerWithRegistry:(NSObject<FlutterPluginRegistry>*)registry;
@end

#endif /* GeneratedPluginRegistrant_h */
